// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebUser.Data;
#nullable disable
namespace WebUser.Migrations
{
    [DbContext(typeof(DB_Context))]
    [Migration("20240408152443_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);
            modelBuilder.Entity("AttributeValuePromotion", b =>
                {
                    b.Property<int>("AttributeValuesID")
                        .HasColumnType("int");
                    b.Property<int>("PromotionsID")
                        .HasColumnType("int");
                    b.HasKey("AttributeValuesID", "PromotionsID");
                    b.HasIndex("PromotionsID");
                    b.ToTable("PromotionAttrValue", (string)null);
                });
            modelBuilder.Entity("CategoryPromotion", b =>
                {
                    b.Property<int>("CategoriesID")
                        .HasColumnType("int");
                    b.Property<int>("PromotionsID")
                        .HasColumnType("int");
                    b.HasKey("CategoriesID", "PromotionsID");
                    b.HasIndex("PromotionsID");
                    b.ToTable("PromotionCategory", (string)null);
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");
                    b.ToTable("AspNetRoles", (string)null);
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);
                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
                    b.HasKey("Id");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetRoleClaims", (string)null);
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);
                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserClaims", (string)null);
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
                    b.HasKey("LoginProvider", "ProviderKey");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserLogins", (string)null);
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");
                    b.HasKey("UserId", "RoleId");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetUserRoles", (string)null);
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");
                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");
                    b.HasKey("UserId", "LoginProvider", "Name");
                    b.ToTable("AspNetUserTokens", (string)null);
                });
            modelBuilder.Entity("ProductPromotion", b =>
                {
                    b.Property<int>("ProductsID")
                        .HasColumnType("int");
                    b.Property<int>("PromotionsID")
                        .HasColumnType("int");
                    b.HasKey("ProductsID", "PromotionsID");
                    b.HasIndex("PromotionsID");
                    b.ToTable("ProductPromotion");
                });
            modelBuilder.Entity("ProductPromotion1", b =>
                {
                    b.Property<int>("PromoProductsID")
                        .HasColumnType("int");
                    b.Property<int>("PromoPromotionsID")
                        .HasColumnType("int");
                    b.HasKey("PromoProductsID", "PromoPromotionsID");
                    b.HasIndex("PromoPromotionsID");
                    b.ToTable("ProductPromotion1");
                });
            modelBuilder.Entity("WebUser.Domain.entities.AttributeName", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.HasKey("ID");
                    b.HasIndex("CategoryId");
                    b.ToTable("AttributeNames");
                });
            modelBuilder.Entity("WebUser.Domain.entities.AttributeValue", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);
                    b.Property<int?>("AttributeNameID")
                        .HasColumnType("int");
                    b.Property<int?>("ProductID")
                        .HasColumnType("int");
                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.HasKey("ID");
                    b.HasIndex("AttributeNameID");
                    b.HasIndex("ProductID");
                    b.ToTable("AttributeValues");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Cart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);
                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
                    b.HasKey("ID");
                    b.HasIndex("UserId");
                    b.ToTable("Carts");
                });
            modelBuilder.Entity("WebUser.Domain.entities.CartItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);
                    b.Property<int>("Amount")
                        .HasColumnType("int");
                    b.Property<int>("CartId")
                        .HasColumnType("int");
                    b.Property<int>("ProductId")
                        .HasColumnType("int");
                    b.HasKey("ID");
                    b.HasIndex("CartId");
                    b.HasIndex("ProductId");
                    b.ToTable("CartItems");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");
                    b.HasKey("ID");
                    b.HasIndex("ParentCategoryId");
                    b.ToTable("Categories");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Coupon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);
                    b.Property<DateTime>("ActiveFrom")
                        .HasColumnType("datetime2");
                    b.Property<DateTime>("ActiveTo")
                        .HasColumnType("datetime2");
                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");
                    b.Property<double>("DiscountVal")
                        .HasColumnType("float");
                    b.Property<bool>("IsActivated")
                        .HasColumnType("bit");
                    b.Property<int?>("OrderId")
                        .HasColumnType("int");
                    b.Property<int?>("OrderProductID")
                        .HasColumnType("int");
                    b.Property<int>("ProductId")
                        .HasColumnType("int");
                    b.HasKey("ID");
                    b.HasIndex("OrderId");
                    b.HasIndex("OrderProductID");
                    b.HasIndex("ProductId");
                    b.ToTable("Coupons");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Discount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);
                    b.Property<DateTime>("ActiveFrom")
                        .HasColumnType("datetime2");
                    b.Property<DateTime>("ActiveTo")
                        .HasColumnType("datetime2");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");
                    b.Property<double>("DiscountVal")
                        .HasColumnType("float");
                    b.Property<int>("ProductId")
                        .HasColumnType("int");
                    b.HasKey("ID");
                    b.HasIndex("ProductId");
                    b.ToTable("Discounts");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Image", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);
                    b.Property<byte[]>("ImageContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");
                    b.Property<int?>("ProductID")
                        .HasColumnType("int");
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");
                    b.HasKey("ID");
                    b.HasIndex("ProductID");
                    b.HasIndex("UserID");
                    b.ToTable("Img");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("int");
                    b.Property<double>("Payment")
                        .HasColumnType("float");
                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");
                    b.Property<int>("PointsUsed")
                        .HasColumnType("int");
                    b.Property<bool>("Status")
                        .HasColumnType("bit");
                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
                    b.HasKey("ID");
                    b.HasIndex("UserId");
                    b.ToTable("Orders");
                });
            modelBuilder.Entity("WebUser.Domain.entities.OrderProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);
                    b.Property<int>("Amount")
                        .HasColumnType("int");
                    b.Property<double>("FinalPrice")
                        .HasColumnType("float");
                    b.Property<int>("OrderId")
                        .HasColumnType("int");
                    b.Property<int>("ProductId")
                        .HasColumnType("int");
                    b.HasKey("ID");
                    b.HasIndex("OrderId");
                    b.HasIndex("ProductId");
                    b.ToTable("OrderProducts");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Point", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);
                    b.Property<int>("BalanceLeft")
                        .HasColumnType("int");
                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");
                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");
                    b.Property<bool>("IsExpirable")
                        .HasColumnType("bit");
                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");
                    b.Property<int?>("OrderId")
                        .HasColumnType("int");
                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
                    b.Property<int>("Value")
                        .HasColumnType("int");
                    b.HasKey("ID");
                    b.HasIndex("OrderId");
                    b.HasIndex("UserId");
                    b.ToTable("Points");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<double>("Price")
                        .HasColumnType("float");
                    b.Property<int>("ReservedStock")
                        .HasColumnType("int");
                    b.Property<int>("Stock")
                        .HasColumnType("int");
                    b.HasKey("ID");
                    b.ToTable("Products");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Promotion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);
                    b.Property<DateTime>("ActiveFrom")
                        .HasColumnType("datetime2");
                    b.Property<DateTime>("ActiveTo")
                        .HasColumnType("datetime2");
                    b.Property<int>("BuyQuantity")
                        .HasColumnType("int");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");
                    b.Property<double>("DiscountVal")
                        .HasColumnType("float");
                    b.Property<int>("GetQuantity")
                        .HasColumnType("int");
                    b.Property<bool>("IsFirstOrder")
                        .HasColumnType("bit");
                    b.Property<double>("MinPay")
                        .HasColumnType("float");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<int>("PointsExpireDays")
                        .HasColumnType("int");
                    b.Property<int>("PointsPercent")
                        .HasColumnType("int");
                    b.Property<int>("PointsValue")
                        .HasColumnType("int");
                    b.HasKey("ID");
                    b.ToTable("PromotionPromProduct", (string)null);
                });
            modelBuilder.Entity("WebUser.Domain.entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");
                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");
                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");
                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");
                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");
                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");
                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");
                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");
                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");
                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");
                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");
                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");
                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");
                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");
                    b.ToTable("AspNetUsers", (string)null);
                });
            modelBuilder.Entity("AttributeValuePromotion", b =>
                {
                    b.HasOne("WebUser.Domain.entities.AttributeValue", null)
                        .WithMany()
                        .HasForeignKey("AttributeValuesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("WebUser.Domain.entities.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("CategoryPromotion", b =>
                {
                    b.HasOne("WebUser.Domain.entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("WebUser.Domain.entities.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebUser.Domain.entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebUser.Domain.entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("WebUser.Domain.entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebUser.Domain.entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("ProductPromotion", b =>
                {
                    b.HasOne("WebUser.Domain.entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("WebUser.Domain.entities.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("ProductPromotion1", b =>
                {
                    b.HasOne("WebUser.Domain.entities.Product", null)
                        .WithMany()
                        .HasForeignKey("PromoProductsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("WebUser.Domain.entities.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromoPromotionsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("WebUser.Domain.entities.AttributeName", b =>
                {
                    b.HasOne("WebUser.Domain.entities.Category", "Category")
                        .WithMany("Attributes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Category");
                });
            modelBuilder.Entity("WebUser.Domain.entities.AttributeValue", b =>
                {
                    b.HasOne("WebUser.Domain.entities.AttributeName", "AttributeName")
                        .WithMany("AttributeValues")
                        .HasForeignKey("AttributeNameID");
                    b.HasOne("WebUser.Domain.entities.Product", "Product")
                        .WithMany("AttributeValues")
                        .HasForeignKey("ProductID");
                    b.Navigation("AttributeName");
                    b.Navigation("Product");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Cart", b =>
                {
                    b.HasOne("WebUser.Domain.entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });
            modelBuilder.Entity("WebUser.Domain.entities.CartItem", b =>
                {
                    b.HasOne("WebUser.Domain.entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("WebUser.Domain.entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Cart");
                    b.Navigation("Product");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Category", b =>
                {
                    b.HasOne("WebUser.Domain.entities.Category", "ParentCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentCategoryId");
                    b.Navigation("ParentCategory");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Coupon", b =>
                {
                    b.HasOne("WebUser.Domain.entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");
                    b.HasOne("WebUser.Domain.entities.OrderProduct", null)
                        .WithMany("ActivatedCoupons")
                        .HasForeignKey("OrderProductID");
                    b.HasOne("WebUser.Domain.entities.Product", "Product")
                        .WithMany("Coupons")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Order");
                    b.Navigation("Product");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Discount", b =>
                {
                    b.HasOne("WebUser.Domain.entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Product");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Image", b =>
                {
                    b.HasOne("WebUser.Domain.entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductID");
                    b.HasOne("WebUser.Domain.entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                    b.Navigation("Product");
                    b.Navigation("User");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Order", b =>
                {
                    b.HasOne("WebUser.Domain.entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });
            modelBuilder.Entity("WebUser.Domain.entities.OrderProduct", b =>
                {
                    b.HasOne("WebUser.Domain.entities.Order", "Order")
                        .WithMany("OrderProduct")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("WebUser.Domain.entities.Product", "Product")
                        .WithMany("OrderProduct")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Order");
                    b.Navigation("Product");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Point", b =>
                {
                    b.HasOne("WebUser.Domain.entities.Order", "Order")
                        .WithMany("Points")
                        .HasForeignKey("OrderId");
                    b.HasOne("WebUser.Domain.entities.User", "User")
                        .WithMany("Points")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Order");
                    b.Navigation("User");
                });
            modelBuilder.Entity("WebUser.Domain.entities.AttributeName", b =>
                {
                    b.Navigation("AttributeValues");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Cart", b =>
                {
                    b.Navigation("Items");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Category", b =>
                {
                    b.Navigation("Attributes");
                    b.Navigation("Subcategories");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Order", b =>
                {
                    b.Navigation("OrderProduct");
                    b.Navigation("Points");
                });
            modelBuilder.Entity("WebUser.Domain.entities.OrderProduct", b =>
                {
                    b.Navigation("ActivatedCoupons");
                });
            modelBuilder.Entity("WebUser.Domain.entities.Product", b =>
                {
                    b.Navigation("AttributeValues");
                    b.Navigation("CartItems");
                    b.Navigation("Coupons");
                    b.Navigation("Images");
                    b.Navigation("OrderProduct");
                });
            modelBuilder.Entity("WebUser.Domain.entities.User", b =>
                {
                    b.Navigation("Orders");
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
